### ISSUE TITLE
stuff i get in the dungeon is not given to me

### ISSUE THREAD

**Issue by tuckergames123** [kieranmillar/Cool-Idle#3]

**Comment by kieranmillar** [comment]
Thanks for the report but this is not a bug. There are two things going on here:
1. The dungeon interface is not finished, the sword and map to a new dungeon are given to the player, but there is not yet an interface to equip the sword or travel to the other dungeon.
2. Powerups collected inside the dungeon instance (all pickups that live outside of chests, like stat gems and health potions) are temporary and are expected to go away when you retire from the instance or die. There will be other means of permanently raising stats, but are not yet impleme ted.

**Comment by tuckergames123** [comment]
thanks
