### ISSUE TITLE
dungeon puzzle impossible

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [kieranmillar/Cool-Idle#5]
From what i can tell, after like 20 attempts there's no winning strategy. I might just be stupid, but i'm not sure.

**Comment by ExplodingHairyPotatoCat** [comment]
Nevermind i'm just fucking stupid

**Comment by kieranmillar** [comment]
Glad you figured it out.

While you're here, mind if I ask you how you found this game? I've never advertised it anywhere, clearly it's very unfinished, but occasionally I get bouts of traffic to it and I'm wondering where it's coming from.

**Comment by ExplodingHairyPotatoCat** [comment]
Looking through the idle games section of GitHub
